Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/CacheController.cs
using Infrastructure.HttpClientService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Model.AppConfig;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Web.Controllers
{
    public class CacheController : Controller
    {
        private readonly IWebCacheServiceClient serviceClient;
        private readonly WebCacheServiceConfiguration config;

        public CacheController(IWebCacheServiceClient serviceClient, IOptions<WebCacheServiceConfiguration> options)
        {
            this.serviceClient = serviceClient;
            this.config = options.Value;
        }

        public async Task<IActionResult> IndexAsync()
        {
            var queryCache = await serviceClient.QueryCache();
            ViewBag.JsonData = Newtonsoft.Json.Linq.JValue.Parse(JsonConvert.SerializeObject(queryCache)).ToString(Newtonsoft.Json.Formatting.Indented);
            ViewBag.BaseURL = config.BaseURL;
            return View();
        }
    }
}

Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Web/Controllers/UserController.cs
using Infrastructure.Factory;
using Infrastructure.HttpClientService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Model;
using Model.AppConfig;

namespace Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IWebCacheServiceClient serviceClient;
        private readonly WebCacheServiceConfiguration config;

        public UserController(IWebCacheServiceClient serviceClient, IOptions<WebCacheServiceConfiguration> options)
        {
            this.serviceClient = serviceClient;
            this.config = options.Value;
        }

        public IActionResult Index()
        {
            ViewBag.BaseURL = config.BaseURL;
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Generate([FromBody] User user)
        {
            List<Task> tasksCreateUser = new List<Task>();
            List<int> sentUser = new List<int>();
            for (int i = 0; i < user.Number; i++)
            {
                var generatedUser = UserFactory.GenerateUser();
                tasksCreateUser.Add(SendUser(generatedUser));
                sentUser.Add(generatedUser.Number);
            }
            Task.WaitAll(tasksCreateUser.ToArray());

            return Json(user);
        }

        private Task SendUser(User user)
        {
            var TCS = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
            try
            {
                Random rnd = new Random();
                int min = 1000, max = 5000;
                Thread.Sleep(rnd.Next(min, max));
                serviceClient.CreateUser(UserFactory.GenerateUser());

                TCS.SetResult();
            }
            catch (Exception e)
            {
                TCS.SetException(new ApplicationException(e.Message));
            }
            return TCS.Task;
        }
    }
}

Web/Views/Cache/Index.cshtml
@using ContactApi.Model
@using Microsoft.AspNetCore.Html
@using Newtonsoft.Json
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<pre>
    @Html.Raw(ViewBag.JsonData)
</pre>

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cache" asp-action="Index">Query Cache</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/Views/User/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model User

<div class="text-center">
    <form id="form-action" method="post" class="row row-cols-lg-auto g-3 align-items-center" role="form">
        <div class="col-12">
            <label class="visually-hidden" for="inlineFormInputGroupUsername">Username</label>
            <div class="input-group">
                <input asp-for="Number" class="form-control" placeholder="n User" id="n-user" />
            </div>
        </div>

        <div class="col-12">
            <input type="submit" class="btn btn-primary" value="Submit" id="btn-submit-user" />
            <div id="loading">loading...</div>
        </div>
    </form>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
    let baseUrl = '@ViewBag.BaseURL';
    $(document).ready(function() {
        console.log("ready!");
        $('#loading').hide();
    });

    $("#btn-submit-user").click(function(e) {
        e.preventDefault();

        $('#btn-submit-user').prop('disabled', true);
        $('#loading').show();

        var nUser = $('#n-user').val();
        console.log("create " + nUser + ' user(s)')
        let users = [];
        for (let i = 0; i < nUser; i++) {
            var user = GenerateUser();
            users.push(user);
        }

        users.forEach(user => {
            let min = Math.ceil(1000);
            let max = Math.floor(5000);
            let delay = randomNumber(min, max);
            setInterval(SendUser, delay, user);
        });

        $('#loading').hide();
        $('#btn-submit-user').prop('disabled', false);
        $('#n-user').val('');
    });

    function SendUser(user) {
        if (user != null) {
            $.ajax({
                type: "POST",
                url: baseUrl + "webserver/",
                data: JSON.stringify(user),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function(response) {
                    if (response != null) {
                        console.log('user ' + user.Number + " created successfully with response !  " + response + " - " + new Date().toLocaleString());
                    } else {
                        alert("Something went wrong");
                    }
                    $('#loading').hide();
                    $('#btn-submit-user').prop('disabled', false);
                    $('#n-user').val('');
                },
                failure: function(response) {
                    alert(response.responseText);
                },
                error: function(response) {
                    alert(response.responseText);
                }
            });
        } else {
            console.log('NOT OK');
        }
        return true;
    }

    function GenerateUser() {
        min = Math.ceil(0);
        max = Math.floor(100000);
        var user = new Object();
        user.Number = Math.round(randomNumber(min, max));
        return user;
    }
    function randomNumber(min, max) {
        return Math.random() * (max - min) + min;
    }
</script>